name: ci

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_NAME: gha-alpha

jobs:
  log_vars:
    environment: test
    env:
      API_URL: ${{ vars.API_URL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Print env vars
        run: |
          echo "Project name : ${{ env.PROJECT_NAME }}"
          echo "API_URL      : ${{ env.API_URL }}"
          echo "DB_HOST      : ${{ env.DB_HOST }}"
          echo "DB_PASSWORD  : ${{ env.DB_PASSWORD }}"
      - name: Get code
        uses: actions/checkout@v3

      - name: Print secrets
        run: |
          node ./scripts/load-secrets.js '${{ toJSON(secrets) }}'

  setup:
    runs-on: ubuntu-latest
    outputs:
      js_file_name: ${{ steps.set-js-file-name.outputs.JS_FILE_NAME }}
    steps:
      - name: Print env vars
        run: |
          echo $PROJECT_NAME
          echo "Project name: ${{ env.PROJECT_NAME }}"
          echo "DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"

      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        id: test
        run: yarn test

      - name: Print failed tests report
        if: failure() && steps.test.outcome == 'failure'
        run: echo "Tests have failed. Crap 😢"

      - name: Build
        run: yarn build

      - name: Publish JS file name
        id: set-js-file-name
        run: echo "JS_FILE_NAME=$(ls dist/*.js)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: setup
    uses: ./.github/workflows/deploy.yml
    with:
      artifact_name: dist
      environment: production
  report:
    needs: [log_vars, setup, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Print github context
        run: echo "${{ toJSON(github) }}"
