name: reusable-deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}

      - name: Output artifact
        run: ls

      - name: Deploy to production
        run: echo "Deploying to ${{ inputs.environment }}"
